"""add meli columns to boats and credentials table

Revision ID: 1f21900c91dd
Revises: 
Create Date: 2026-04-26 21:10:18.196138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f21900c91dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meli_listings', schema=None) as batch_op:
        batch_op.drop_index('ix_meli_listings_boat_id')
        batch_op.drop_index('ix_meli_listings_site_id')

    op.drop_table('meli_listings')
    with op.batch_alter_table('boats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meli_mlu_item_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('meli_mlu_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('meli_mlu_permalink', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('meli_mlu_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('meli_mla_item_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('meli_mla_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('meli_mla_permalink', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('meli_mla_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boats', schema=None) as batch_op:
        batch_op.drop_column('meli_mla_synced_at')
        batch_op.drop_column('meli_mla_permalink')
        batch_op.drop_column('meli_mla_status')
        batch_op.drop_column('meli_mla_item_id')
        batch_op.drop_column('meli_mlu_synced_at')
        batch_op.drop_column('meli_mlu_permalink')
        batch_op.drop_column('meli_mlu_status')
        batch_op.drop_column('meli_mlu_item_id')

    op.create_table('meli_listings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('boat_id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('meli_item_id', sa.VARCHAR(length=30), nullable=True),
    sa.Column('meli_permalink', sa.VARCHAR(length=500), nullable=True),
    sa.Column('meli_status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('sync_error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boat_id', 'site_id', name='uq_meli_listing_boat_site')
    )
    with op.batch_alter_table('meli_listings', schema=None) as batch_op:
        batch_op.create_index('ix_meli_listings_site_id', ['site_id'], unique=False)
        batch_op.create_index('ix_meli_listings_boat_id', ['boat_id'], unique=False)

    # ### end Alembic commands ###
